"""inicial

Revision ID: d10d257735d7
Revises: 
Create Date: 2026-06-26 23:06:19.262881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10d257735d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)
        batch_op.create_index(batch_op.f('ix_categorias_slug'), ['slug'], unique=True)

    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_qr', sa.String(length=255), nullable=True),
    sa.Column('titular', sa.String(length=150), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_nombre'), ['nombre'], unique=True)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('carritos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carritos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_pedido', sa.String(length=40), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('direccion_entrega', sa.String(length=300), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_numero_pedido'), ['numero_pedido'], unique=True)
        batch_op.create_index(batch_op.f('ix_pedidos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('comprobantes_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=False),
    sa.Column('imagen_comprobante', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('revisado_por', sa.Integer(), nullable=True),
    sa.Column('revisado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['revisado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comprobantes_pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprobantes_pago_pedido_id'), ['pedido_id'], unique=False)

    op.create_table('detalle_carrito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrito_id', 'producto_id', name='uq_carrito_producto')
    )
    with op.batch_alter_table('detalle_carrito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detalle_carrito_carrito_id'), ['carrito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalle_carrito_producto_id'), ['producto_id'], unique=False)

    op.create_table('detalle_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detalle_pedido_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalle_pedido_producto_id'), ['producto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalle_pedido_producto_id'))
        batch_op.drop_index(batch_op.f('ix_detalle_pedido_pedido_id'))

    op.drop_table('detalle_pedido')
    with op.batch_alter_table('detalle_carrito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalle_carrito_producto_id'))
        batch_op.drop_index(batch_op.f('ix_detalle_carrito_carrito_id'))

    op.drop_table('detalle_carrito')
    with op.batch_alter_table('comprobantes_pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprobantes_pago_pedido_id'))

    op.drop_table('comprobantes_pago')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_numero_pedido'))
        batch_op.drop_index(batch_op.f('ix_pedidos_estado'))

    op.drop_table('pedidos')
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carritos_usuario_id'))

    op.drop_table('carritos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))
        batch_op.drop_index(batch_op.f('ix_productos_categoria_id'))

    op.drop_table('productos')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_nombre'))

    op.drop_table('roles')
    op.drop_table('metodos_pago')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_slug'))
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))

    op.drop_table('categorias')
    # ### end Alembic commands ###
